### ISSUE TITLE
Details toggle no longer toggling

### ISSUE THREAD

**Issue by mavrik-kl** [tonycpsu/panwid#12]
Hello. I am having trouble getting toggle_details() to work in examples/datatable.py. When you enter '.' on a given row, the details will appear, but if you enter '.' again, they remain (i.e., they do not disappear). My local workaround was to override toggle_details() as shown in the attached diff, but I'm wondering if the root problem is that open_details() in panwid/datatable/rows.py is not setting self['_details']['open'] to True? I see that close_details() does set this value to False as a matter of course. Thanks.
[datatable.py.diff.txt](https://github.com/tonycpsu/panwid/files/3070341/datatable.py.diff.txt)

**Comment by tonycpsu** [comment]
Good catch -- thanks!
