### ISSUE TITLE
pypi latest release (v0.2.5) cannot be imported on Python 3.9+

### ISSUE THREAD

**Issue by rmartin16** [tonycpsu/panwid#17]
Hello,
I use `panwid` in a semi-personal project and I noticed it stops working on python 3.9. This is an upstream problem technically since it's `blist` that stops working.

I see you've been making progress towards a 0.3.* release. Any ideas on timing for the next release? (i understand you probably spend your free time on this....so, if you don't know, that's fine too :) )

Or do you think any of these `dev` releases for 0.3 might be stable enough to try? Im mostly just trying to weigh my options for moving to python 3.9.

Thanks!

**Comment by tonycpsu** [comment]
The blist dependency has been gone since dec69b72 with the update to `raccoon` 3.0.0.  By all means go ahead and try a dev release, but things are changing quite a bit and not well-documented, so I've been hesitant to put out a standard release in PyPi until I've cleaned things up some.

**Comment by rmartin16** [comment]
Good deal. I'll give `v0.3.2.dev0` a go for now with the requirement below and roll with the punches.

```
panwid @ git+git://github.com/tonycpsu/panwid@v0.3.2.dev0
```

Thanks for the information and this library.
