### ISSUE TITLE
How to make datatable auto resize to full screen?

### ISSUE THREAD

**Issue by laixintao** [tonycpsu/panwid#3]
Hi, I am creating a wireshark clone on terminal, thanks to your awesome work!

![image](https://user-images.githubusercontent.com/9675939/36765644-33a4498e-1c6d-11e8-8ea4-aba0f0b903a6.png)

And I have few questions about your datatable.

1. ~~How to make Column not wrap to next line? If current Column not long enough to display value, just cut it.~~ Found `wrap` paramter, useful!
2. What `footer_fn` (https://github.com/tonycpsu/panwid/blob/master/panwid/datatable/datatable.py#L47) use for? I just see you set it but don't use it in anywhere.

**Comment by tonycpsu** [comment]
It's used in `cells.py`.  See [here](https://github.com/tonycpsu/panwid/blob/61b88ad276ef5b2f1b3eabbbca535e9951350d1d/examples/datatable_test.py#L67).
