### ISSUE TITLE
Refresh datatable after MainLoop running?

### ISSUE THREAD

**Issue by laixintao** [tonycpsu/panwid#5]
Hi, sorry to bother again. Is there a way to refresh datatable after MainLoop running?  My data is huge, so I want to dynamic `add_row()` after drawing the UI.

I tried `Datatable.add_row()`. When I use it before `MainLoop.run()` it works fine, but when I use it after `MainLoop.run()` , the new data wasn't added to GUI table.

I want to something like [urwid.Text.set_text](http://urwid.org/reference/widget.html#urwid.Text.set_text).

Thanks.

**Comment by tonycpsu** [comment]
`add_row` works for me.  You can test it by running examples/datatable.py and typing "a".  See [here](https://github.com/tonycpsu/panwid/blob/master/examples/datatable.py#L192).

**Comment by laixintao** [comment]
Thanks, it works actually, I met some problems with asyncio. Resolved already 👍
